# Generated by Django 3.0.5 on 2020-04-07 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asu', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
