# Generated by Django 3.0.5 on 2020-04-09 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asu', '0002_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GroupLesson',
        ),
    ]
