# Generated by Django 3.0.5 on 2020-04-09 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asu', '0003_delete_grouplesson'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupLesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asu.Group')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asu.Lesson')),
            ],
        ),
    ]
