# Generated by Django 3.0.5 on 2020-04-09 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asu', '0004_grouplesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='asu.Group'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='GroupLesson',
        ),
    ]
